---
- name: Install microk8s Canonical Kubernetes
  snap:
    name: microk8s
    classic: yes
  notify: 
    - reboot machine
    - wait for microk8s up
    - install microk8s addons

- name: add /snap/bin to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/snap/bin).*?)(["]*)$'
    line="PATH=\1\2:/snap/bin\3"

- name: Setup Bash microuK8s alias
  lineinfile:
    dest: "/etc/bash_aliases"
    create: yes
    group: root
    line: "alias kubectl='microk8s kubectl'"
    mode: "0644"
    owner: root
    regexp: "^alias kubectl="

- name: Source aliases file
  lineinfile:
    dest: /etc/bash.bashrc
    line: "source /etc/bash_aliases"
    state: present

- meta: flush_handlers